name: Build and Release Caddy v2.10.2

on:
  #schedule:
    #- cron: '0 3 * * *'
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  build_version: v2.10.2
  build_config:  --with github.com/WeidiDeng/caddy-cloudflare-ip --with github.com/mholt/caddy-grpc-web --with github.com/greenpau/caddy-git@v1.0.9 --with github.com/mholt/caddy-webdav --with github.com/WingLim/caddy-webhook@v1.0.8 --with github.com/mholt/caddy-ratelimit --with github.com/caddyserver/ntlm-transport@v0.1.2 --with github.com/lolPants/caddy-requestid@v1.1.2 --with github.com/sjtug/caddy2-filter --with github.com/chukmunnlee/caddy-openapi@v0.11.0 --with github.com/ggicci/caddy-jwt@v0.12.0 --with github.com/caddy-dns/cloudflare --with github.com/libdns/cloudflare@v0.1.2 --with github.com/caddy-dns/route53@v1.5.1 --with github.com/caddy-dns/duckdns@v0.4.0 --with github.com/caddy-dns/dnspod@v0.0.4 --with github.com/caddy-dns/digitalocean --with github.com/caddy-dns/alidns@v1.0.23 --with github.com/caddy-dns/godaddy@v1.0.3 --with github.com/caddy-dns/vultr --with github.com/caddy-dns/googleclouddns@v1.0.4 --with github.com/caddy-dns/ovh@v0.0.3 --with github.com/caddy-dns/metaname@v0.2.0 --with github.com/caddy-dns/ddnss --with github.com/caddy-dns/dinahosting --with github.com/caddy-dns/powerdns@v1.0.1 --with github.com/caddy-dns/tencentcloud@v0.2.1 --with github.com/aksdb/caddy-cgi/v2@v2.2.5 --with github.com/mholt/caddy-l4 --with github.com/caddyserver/replace-response --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive 

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check Server Performance
        run: |
          echo "警告⚠"
          echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
          echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo "CPU核心数量: $(nproc)"
          echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
          echo "--------------------------内存信息--------------------------"
          echo "已安装内存详细信息:"
          echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
          echo "--------------------------硬盘信息--------------------------"
          echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.2'

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          
      - name: Build Caddy for Linux amd64
        run: |
          export GOOS=linux
          export GOARCH=amd64
          xcaddy build $build_version $build_config --output ./build_caddy/caddy_linux_amd64

      - name: Build Caddy for Linux arm64
        run: |
          export GOOS=linux
          export GOARCH=arm64
          xcaddy build $build_version $build_config --output ./build_caddy/caddy_linux_arm64

      - name: Build Caddy for Linux arm
        run: |
          export GOOS=linux
          export GOARCH=arm
          xcaddy build $build_version $build_config --output ./build_caddy/caddy_linux_arm

      - name: Build Caddy for macOS amd64
        run: |
          export GOOS=darwin
          export GOARCH=amd64
          xcaddy build $build_version $build_config --output ./build_caddy/caddy_darwin_amd64

      - name: Build Caddy for macOS arm64
        run: |
          export GOOS=darwin
          export GOARCH=arm64
          xcaddy build $build_version $build_config --output ./build_caddy/caddy_darwin_arm64

      - name: Build Caddy for Windows amd64
        run: |
          export GOOS=windows
          export GOARCH=amd64
          xcaddy build $build_version $build_config --output ./build_caddy/caddy_windows_amd64.exe

      - name: intEnv
        run: |
          echo "DATE=$(date +"%Y-%m-%d_%H:%M:%S")" >> $GITHUB_ENV
          chmod +x ./build_caddy/caddy_linux_amd64
          ./build_caddy/caddy_linux_amd64 list-modules > ./build_caddy/build-modules.info
          cd ./build_caddy/
          echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: caddy-${{ env.build_version }}
          files: |
            ./build_caddy/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: caddy-${{ env.build_version }}
          files: |
            ./build_caddy/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
