name: Build caddy

on:
  workflow_dispatch:

  release:
    types:
      - 'prereleased'
      - 'published'
      - 'released'

  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - { name: "windows-386", GOARCH: 386, GOOS: windows, release: true }
        - { name: "windows-amd64", GOARCH: amd64, GOOS: windows, release: true }
        - { name: "linux-amd64", GOARCH: amd64, GOOS: linux, release: true }
        - { name: "linux-arm64", GOARCH: arm64, GOOS: linux, release: true }
        - { name: "linux-armv5", GOARCH: arm, GOARM: 5, GOOS: linux, release: true }
        - { name: "linux-s390x", GOARCH: s390x, GOOS: linux, release: true }
        - { name: "freebsd-amd64", GOARCH: amd64, GOOS: freebsd, release: true }
        - { name: "freebsd-arm64", GOARCH: arm64, GOOS: freebsd, release: true }
        - { name: "darwin-amd64", GOARCH: amd64, GOOS: darwin, release: true }
        - { name: "darwin-arm64", GOARCH: arm64, GOOS: darwin, release: true }

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21.1'
        check-latest: true

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.config.GOARCH }}-modules-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.config.GOARCH }}-modules-

    - name: Install xcaddy
      run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: Build caddy
      run: |
        mkdir -p release-tmp
        export GOARCH=${{ matrix.config.GOARCH }}
        export GOOS=${{ matrix.config.GOOS }}
        ~/go/bin/xcaddy build \
          --with github.com/WeidiDeng/caddy-cloudflare-ip \
          --with github.com/mholt/caddy-grpc-web \
          --with github.com/greenpau/caddy-git \
          --with github.com/mholt/caddy-webdav \
          --with github.com/WingLim/caddy-webhook \
          --with github.com/mholt/caddy-ratelimit \
          --with github.com/caddyserver/ntlm-transport \
          --with github.com/lolPants/caddy-requestid \
          --with github.com/sjtug/caddy2-filter \
          --with github.com/chukmunnlee/caddy-openapi \
          --with github.com/ggicci/caddy-jwt \
          --with github.com/caddy-dns/cloudflare \
          --with github.com/libdns/cloudflare \
          --with github.com/caddy-dns/route53 \
          --with github.com/caddy-dns/duckdns \
          --with github.com/caddy-dns/dnspod \
          --with github.com/caddy-dns/digitalocean \
          --with github.com/caddy-dns/alidns \
          --with github.com/caddy-dns/godaddy \
          --with github.com/caddy-dns/vultr \
          --with github.com/caddy-dns/googleclouddns \
          --with github.com/caddy-dns/ovh \
          --with github.com/caddy-dns/metaname \
          --with github.com/caddy-dns/ddnss \
          --with github.com/caddy-dns/dinahosting \
          --with github.com/caddy-dns/powerdns \
          --with github.com/caddy-dns/tencentcloud \
          --with github.com/aksdb/caddy-cgi/v2 \
          --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive \
          --output ./release-tmp/caddy

    - name: Rename for Windows
      if: matrix.config.GOOS == 'windows'
      run: mv ./release-tmp/caddy ./release-tmp/caddy.exe

    - name: Calculate Hash
      run: |
        cd ./release-tmp || exit 1
        sha256sum * > sha256

    - name: Archive build artifacts
      run: |
        mkdir -p release-ready
        cd ./release-tmp
        if [ "${{ matrix.config.GOOS }}" == "windows" ]; then
          zip -r ../release-ready/caddy-${{ matrix.config.name }}.zip *
        else
          tar -zcvf ../release-ready/caddy-${{ matrix.config.name }}.tar.gz *
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: caddy-${{ github.sha }}-${{ matrix.config.name }}
        path: ./release-ready/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: github.event_name == 'release' && matrix.config.release
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: >
          Release for ${{ github.ref }} - ${{ matrix.config.name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      if: github.event_name == 'release' && matrix.config.release
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-ready/*${{ matrix.config.name }}.*
        asset_name: caddy-${{ matrix.config.name }}-${{ github.sha }}
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
