name: Build and Release Caddy

on:
  #schedule:
    #- cron: '0 3 * * *'
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Server Performance
        run: |
          echo "警告⚠"
          echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
          echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo "CPU核心数量: $(nproc)"
          echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
          echo "--------------------------内存信息--------------------------"
          echo "已安装内存详细信息:"
          echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
          echo "--------------------------硬盘信息--------------------------"
          echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.1'

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      # - name: Initialize go.mod and pin dependencies
      #   run: |
      #     go mod init caddybuild
      #     go get github.com/caddyserver/caddy/v2@v2.84
      #     go get github.com/caddyserver/certmagic@v0.21.6
      #     go get github.com/libdns/libdns@v0.2.3
      #     go mod tidy

      # - name: Verify go.mod
      #   run: |
      #     cat go.mod
      #     cat go.sum
      #     go mod verify

      # - name: Debug dependencies
      #   run: |
      #     go version
      #     go env
      #     echo "libdns dependencies:"
      #     go mod graph | grep libdns || echo "No libdns dependencies found"
      #     echo "certmagic dependencies:"
      #     go mod graph | grep certmagic || echo "No certmagic dependencies found"
          
      - name: Build Caddy for Linux amd64
        run: |
          export GOOS=linux
          export GOARCH=amd64
          xcaddy build v2.8.4 \
              --with github.com/WeidiDeng/caddy-cloudflare-ip \
              --with github.com/mholt/caddy-grpc-web \
              --with github.com/greenpau/caddy-git \
              --with github.com/mholt/caddy-webdav \
              --with github.com/WingLim/caddy-webhook \
              --with github.com/mholt/caddy-ratelimit \
              --with github.com/caddyserver/ntlm-transport \
              --with github.com/lolPants/caddy-requestid \
              --with github.com/sjtug/caddy2-filter \
              --with github.com/chukmunnlee/caddy-openapi \
              --with github.com/ggicci/caddy-jwt \
              --with github.com/caddy-dns/cloudflare \
              --with github.com/libdns/cloudflare \
              --with github.com/caddy-dns/route53 \
              --with github.com/caddy-dns/duckdns \
              --with github.com/caddy-dns/dnspod \
              --with github.com/caddy-dns/digitalocean \
              --with github.com/caddy-dns/alidns \
              --with github.com/caddy-dns/godaddy \
              --with github.com/caddy-dns/vultr \
              --with github.com/caddy-dns/googleclouddns \
              --with github.com/caddy-dns/ovh \
              --with github.com/caddy-dns/metaname \
              --with github.com/caddy-dns/ddnss \
              --with github.com/caddy-dns/dinahosting \
              --with github.com/caddy-dns/powerdns \
              --with github.com/caddy-dns/tencentcloud \
              --with github.com/aksdb/caddy-cgi/v2 \
              --with github.com/mholt/caddy-l4 \
              --with github.com/caddyserver/replace-response \
              --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive \
              --output ./caddy_linux_amd64

      - name: Build Caddy for Linux arm64
        run: |
          export GOOS=linux
          export GOARCH=arm64
          xcaddy build v2.8.4 \
              --with github.com/WeidiDeng/caddy-cloudflare-ip \
              --with github.com/mholt/caddy-grpc-web \
              --with github.com/greenpau/caddy-git \
              --with github.com/mholt/caddy-webdav \
              --with github.com/WingLim/caddy-webhook \
              --with github.com/mholt/caddy-ratelimit \
              --with github.com/caddyserver/ntlm-transport \
              --with github.com/lolPants/caddy-requestid \
              --with github.com/sjtug/caddy2-filter \
              --with github.com/chukmunnlee/caddy-openapi \
              --with github.com/ggicci/caddy-jwt \
              --with github.com/caddy-dns/cloudflare \
              --with github.com/libdns/cloudflare \
              --with github.com/caddy-dns/route53 \
              --with github.com/caddy-dns/duckdns \
              --with github.com/caddy-dns/dnspod \
              --with github.com/caddy-dns/digitalocean \
              --with github.com/caddy-dns/alidns \
              --with github.com/caddy-dns/godaddy \
              --with github.com/caddy-dns/vultr \
              --with github.com/caddy-dns/googleclouddns \
              --with github.com/caddy-dns/ovh \
              --with github.com/caddy-dns/metaname \
              --with github.com/caddy-dns/ddnss \
              --with github.com/caddy-dns/dinahosting \
              --with github.com/caddy-dns/powerdns \
              --with github.com/caddy-dns/tencentcloud \
              --with github.com/aksdb/caddy-cgi/v2 \
              --with github.com/mholt/caddy-l4 \
              --with github.com/caddyserver/replace-response \
              --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive \
              --output ./caddy_linux_arm64

      - name: Build Caddy for Linux arm
        run: |
          export GOOS=linux
          export GOARCH=arm
          xcaddy build v2.8.4 \
              --with github.com/WeidiDeng/caddy-cloudflare-ip \
              --with github.com/mholt/caddy-grpc-web \
              --with github.com/greenpau/caddy-git \
              --with github.com/mholt/caddy-webdav \
              --with github.com/WingLim/caddy-webhook \
              --with github.com/mholt/caddy-ratelimit \
              --with github.com/caddyserver/ntlm-transport \
              --with github.com/lolPants/caddy-requestid \
              --with github.com/sjtug/caddy2-filter \
              --with github.com/chukmunnlee/caddy-openapi \
              --with github.com/ggicci/caddy-jwt \
              --with github.com/caddy-dns/cloudflare \
              --with github.com/libdns/cloudflare \
              --with github.com/caddy-dns/route53 \
              --with github.com/caddy-dns/duckdns \
              --with github.com/caddy-dns/dnspod \
              --with github.com/caddy-dns/digitalocean \
              --with github.com/caddy-dns/alidns \
              --with github.com/caddy-dns/godaddy \
              --with github.com/caddy-dns/vultr \
              --with github.com/caddy-dns/googleclouddns \
              --with github.com/caddy-dns/ovh \
              --with github.com/caddy-dns/metaname \
              --with github.com/caddy-dns/ddnss \
              --with github.com/caddy-dns/dinahosting \
              --with github.com/caddy-dns/powerdns \
              --with github.com/caddy-dns/tencentcloud \
              --with github.com/aksdb/caddy-cgi/v2 \
              --with github.com/mholt/caddy-l4 \
              --with github.com/caddyserver/replace-response \
              --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive \
              --output ./caddy_linux_arm

      - name: Build Caddy for macOS amd64
        run: |
          export GOOS=darwin
          export GOARCH=amd64
          xcaddy build v2.8.4 \
              --with github.com/WeidiDeng/caddy-cloudflare-ip \
              --with github.com/mholt/caddy-grpc-web \
              --with github.com/greenpau/caddy-git \
              --with github.com/mholt/caddy-webdav \
              --with github.com/WingLim/caddy-webhook \
              --with github.com/mholt/caddy-ratelimit \
              --with github.com/caddyserver/ntlm-transport \
              --with github.com/lolPants/caddy-requestid \
              --with github.com/sjtug/caddy2-filter \
              --with github.com/chukmunnlee/caddy-openapi \
              --with github.com/ggicci/caddy-jwt \
              --with github.com/caddy-dns/cloudflare \
              --with github.com/libdns/cloudflare \
              --with github.com/caddy-dns/route53 \
              --with github.com/caddy-dns/duckdns \
              --with github.com/caddy-dns/dnspod \
              --with github.com/caddy-dns/digitalocean \
              --with github.com/caddy-dns/alidns \
              --with github.com/caddy-dns/godaddy \
              --with github.com/caddy-dns/vultr \
              --with github.com/caddy-dns/googleclouddns \
              --with github.com/caddy-dns/ovh \
              --with github.com/caddy-dns/metaname \
              --with github.com/caddy-dns/ddnss \
              --with github.com/caddy-dns/dinahosting \
              --with github.com/caddy-dns/powerdns \
              --with github.com/caddy-dns/tencentcloud \
              --with github.com/aksdb/caddy-cgi/v2 \
              --with github.com/mholt/caddy-l4 \
              --with github.com/caddyserver/replace-response \
              --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive \
              --output ./caddy_darwin_amd64

      - name: Build Caddy for macOS arm64
        run: |
          export GOOS=darwin
          export GOARCH=arm64
          xcaddy build v2.8.4 \
              --with github.com/WeidiDeng/caddy-cloudflare-ip \
              --with github.com/mholt/caddy-grpc-web \
              --with github.com/greenpau/caddy-git \
              --with github.com/mholt/caddy-webdav \
              --with github.com/WingLim/caddy-webhook \
              --with github.com/mholt/caddy-ratelimit \
              --with github.com/caddyserver/ntlm-transport \
              --with github.com/lolPants/caddy-requestid \
              --with github.com/sjtug/caddy2-filter \
              --with github.com/chukmunnlee/caddy-openapi \
              --with github.com/ggicci/caddy-jwt \
              --with github.com/caddy-dns/cloudflare \
              --with github.com/libdns/cloudflare \
              --with github.com/caddy-dns/route53 \
              --with github.com/caddy-dns/duckdns \
              --with github.com/caddy-dns/dnspod \
              --with github.com/caddy-dns/digitalocean \
              --with github.com/caddy-dns/alidns \
              --with github.com/caddy-dns/godaddy \
              --with github.com/caddy-dns/vultr \
              --with github.com/caddy-dns/googleclouddns \
              --with github.com/caddy-dns/ovh \
              --with github.com/caddy-dns/metaname \
              --with github.com/caddy-dns/ddnss \
              --with github.com/caddy-dns/dinahosting \
              --with github.com/caddy-dns/powerdns \
              --with github.com/caddy-dns/tencentcloud \
              --with github.com/aksdb/caddy-cgi/v2 \
              --with github.com/mholt/caddy-l4 \
              --with github.com/caddyserver/replace-response \
              --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive \
              --output ./caddy_darwin_arm64

      - name: Build Caddy for Windows amd64
        run: |
          export GOOS=windows
          export GOARCH=amd64
          xcaddy build v2.8.4 \
              --with github.com/WeidiDeng/caddy-cloudflare-ip \
              --with github.com/mholt/caddy-grpc-web \
              --with github.com/greenpau/caddy-git \
              --with github.com/mholt/caddy-webdav \
              --with github.com/WingLim/caddy-webhook \
              --with github.com/mholt/caddy-ratelimit \
              --with github.com/caddyserver/ntlm-transport \
              --with github.com/lolPants/caddy-requestid \
              --with github.com/sjtug/caddy2-filter \
              --with github.com/chukmunnlee/caddy-openapi \
              --with github.com/ggicci/caddy-jwt \
              --with github.com/caddy-dns/cloudflare \
              --with github.com/libdns/cloudflare \
              --with github.com/caddy-dns/route53 \
              --with github.com/caddy-dns/duckdns \
              --with github.com/caddy-dns/dnspod \
              --with github.com/caddy-dns/digitalocean \
              --with github.com/caddy-dns/alidns \
              --with github.com/caddy-dns/godaddy \
              --with github.com/caddy-dns/vultr \
              --with github.com/caddy-dns/googleclouddns \
              --with github.com/caddy-dns/ovh \
              --with github.com/caddy-dns/metaname \
              --with github.com/caddy-dns/ddnss \
              --with github.com/caddy-dns/dinahosting \
              --with github.com/caddy-dns/powerdns \
              --with github.com/caddy-dns/tencentcloud \
              --with github.com/aksdb/caddy-cgi/v2 \
              --with github.com/mholt/caddy-l4 \
              --with github.com/caddyserver/replace-response \
              --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive \
              --output ./caddy_windows_amd64.exe

      - name: intEnv
        run: |
          echo "DATE=$(date +"%Y-%m-%d_%H:%M:%S")" >> $GITHUB_ENV
          chmod +x ./caddy_linux_amd64
          ./caddy_linux_amd64 list-modules > ./build-modules.info
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: caddy-v2.8.4
          files: |
            ./build-modules.info
            ./caddy_linux_amd64
            ./caddy_linux_arm64
            ./caddy_linux_arm
            ./caddy_darwin_amd64
            ./caddy_darwin_arm64
            ./caddy_windows_amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: caddy-v2.8.4
          files: |
            ./build-modules.info
            ./caddy_linux_amd64
            ./caddy_linux_arm64
            ./caddy_linux_arm
            ./caddy_darwin_amd64
            ./caddy_darwin_arm64
            ./caddy_windows_amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
